const staticLayout = {
  [STRUCTURE_SPAWN]: [
    [-1, 0],
    [-1, -1],
    [1, -1],
  ],
  [STRUCTURE_POWER_SPAWN]: [[0, -1]],
  [STRUCTURE_FACTORY]: [[1, 0]],
  [STRUCTURE_LINK]: [[1, 1]],
  [STRUCTURE_STORAGE]: [[0, 1]],
  [STRUCTURE_TERMINAL]: [[-1, 1]],
  [STRUCTURE_NUKER]: [[3, -1]],
  [STRUCTURE_TOWER]: [
    [-1, -3],
    [-3, -1],
    [-3, 1],
    [-1, 3],
    [1, 3],
    [3, 1],
  ],
  [STRUCTURE_ROAD]: [
    [-2, -2],
    [-1, -2],
    [0, -2],
    [1, -2],
    [2, -2],
    [2, -1],
    [2, 0],
    [2, 1],
    [2, 2],
    [1, 2],
    [0, 2],
    [-1, 2],
    [-2, 2],
    [-2, 1],
    [-2, 0],
    [-2, -1],
    [-5, -5],
    [-4, -4],
    [-3, -3],
    [0, -5],
    [0, -4],
    [0, -3],
    [5, -5],
    [4, -4],
    [3, -3],
    [5, 0],
    [4, 0],
    [3, 0],
    [5, 5],
    [4, 4],
    [3, 3],
    [0, 5],
    [0, 4],
    [0, 3],
    [-5, 5],
    [-4, 4],
    [-3, 3],
    [-5, 0],
    [-4, 0],
    [-3, 0],
  ],
  [STRUCTURE_LAB]: [
    [-4, 3],
    [-3, 4],
    [-3, 2],
    [-2, 3],
    [-4, 2],
    [-2, 4],
    [-5, 3],
    [-3, 5],
    [-5, 4],
    [-4, 5],
  ],
  [STRUCTURE_OBSERVER]: [[-2, 5]],
  [STRUCTURE_EXTENSION]: [
    [-3, -2],
    [-2, -3],
    [1, -3],
    [2, -3],
    [3, -2],
    [3, 2],
    [2, 3],
    [-4, 1],
    [-4, -1],
    [-4, -2],
    [-4, -3],
    [-3, -4],
    [-2, -4],
    [-5, -3],
    [-5, -4],
    [-4, -5],
    [-3, -5],
    [-1, -4],
    [1, -4],
    [1, -5],
    [-1, -5],
    [2, -4],
    [3, -4],
    [4, -3],
    [4, -2],
    [5, -3],
    [5, -4],
    [4, -5],
    [3, -5],
    [4, -1],
    [4, 1],
    [5, -1],
    [5, 1],
    [4, 2],
    [2, 4],
    [3, 4],
    [4, 3],
    [5, 3],
    [3, 5],
    [4, 5],
    [5, 4],
    [-1, 4],
    [1, 4],
    [1, 5],
    [-1, 5],
    [-5, 1],
    [-5, -1],
  ],
  [STRUCTURE_EXTRACTOR]: [],
  [STRUCTURE_WALL]: [],
  [STRUCTURE_RAMPART]: [],
  [STRUCTURE_CONTAINER]: [],
};

const controllerLevelStructures = [
  { [STRUCTURE_SPAWN]: 1 },
  { [STRUCTURE_EXTENSION]: 5 },
  { [STRUCTURE_EXTENSION]: 10, [STRUCTURE_TOWER]: 1 },
  { [STRUCTURE_EXTENSION]: 20, [STRUCTURE_STORAGE]: 1, [STRUCTURE_ROAD]: 2500 },
  { [STRUCTURE_EXTENSION]: 30, [STRUCTURE_LINK]: 2, [STRUCTURE_TOWER]: 2 },
  {
    [STRUCTURE_EXTENSION]: 40,
    [STRUCTURE_EXTRACTOR]: 1,
    [STRUCTURE_LAB]: 3,
    [STRUCTURE_LINK]: 3,
    [STRUCTURE_TERMINAL]: 1,
  },
  {
    [STRUCTURE_EXTENSION]: 50,
    [STRUCTURE_FACTORY]: 1,
    [STRUCTURE_LAB]: 6,
    [STRUCTURE_LINK]: 4,
    [STRUCTURE_SPAWN]: 2,
    [STRUCTURE_TOWER]: 3,
  },
  {
    [STRUCTURE_EXTENSION]: 60,
    [STRUCTURE_LAB]: 10,
    [STRUCTURE_LINK]: 6,
    [STRUCTURE_NUKER]: 1,
    [STRUCTURE_OBSERVER]: 1,
    [STRUCTURE_POWER_SPAWN]: 1,
    [STRUCTURE_SPAWN]: 3,
    [STRUCTURE_TOWER]: 6,
  },
];

export { staticLayout, controllerLevelStructures };
